---
title: "Northern Spotted Owl"
author: "Brad Anderson"
date: "January 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
# Install and load the package
devtools::install_github("brucekendall/mpmtools")
library(mpmtools)

library(tidyverse)
library(popbio)
library(mpmtools)
library(primer)
```

```{r}

#class_names <- c("Subadult", "Adult")
#A <- matrix(c(0, 0.024432,
  #            0.71, .094),
  #          nrow = 2, ncol = 2, byrow = TRUE, dimnames=list(class_names, class_names))

#n_0 <- c(1000, 10) # Initial abundance
#pop <- pop.projection(A, n_0, iterations = 10) # Project the matrixpop
#stage.vector.plot(pop$stage.vector) # Plot each stage through time

#lambda(A)

#stable.stage(A)
```

```{r}
class_names <- c("Juvenile", "Subadult", "Adult")

demog_sched <- data.frame(x = 0:3,
                          sx = c(0.108, 0.71, 0.942, 0.942),
                          mx = c(0,0,0,0.24))
owl_matrix <- make_Leslie_matrix(demog_sched, model = "pre")

rownames(owl_matrix) <- c("Juvenile", "Subadult", "Adult")
colnames(owl_matrix) <- c("Juvenile", "Subadult", "Adult")

owl_matrix
lambda(owl_matrix)
DemoInfo(owl_matrix)
stable.stage(owl_matrix)
```

```{r}
n_0 <- c(100,250,1000) # Initial abundance
owl_pop <- pop.projection(owl_matrix, n_0, iterations = 10) # Project the matrixpop
stage.vector.plot(owl_pop$stage.vector) # Plot each stage through time
```

```{r}

plot(owl_pop$pop.sizes)
plot(owl_pop$pop.changes)

```

**b.	Increase egg/hatchling survival in the model, and re-calculate λ1. By how much does it increase? Experiment with different values of this survival term until you get an asymptotic growth rate of 1 or more. How large does egg survival need to be to achieve this? **


```{r}

#Dispersal coefficient
D <- .18
#Newborn/feldging survival
B <- 0.6
#Adult survival
A <- 0.942
#Subadult survival
S <- 0.71
#Fertility 
F <- 0.24


owl_mgmt <- matrix(c(0,    0, (F*B*D),
                      S,    0,            0,
                      0,    A,           A),
                    
nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(class_names, class_names))

lambda(owl_mgmt)

```

If we increase dispersal from 0.18 to 0.6 we can get lambda >1.

```{r}

#Dispersal coefficient
D <- .18
#Newborn/feldging survival
B <- 0.6
#Adult survival
A <- 0.942
#Subadult survival
S <- 0.71
#Fertility 
F <- 0.24


owl_test <- matrix(c(0,    0, (F*B*D),
                      S,    0,            0,
                      0,    A,           A),
                    
nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(class_names, class_names))

lambda(owl_test)

```